-- Generated by v3/scripts/export_prototype_rule_catalog.js
-- Seeds prototype addition families and branches into addition / addition_branch.
START TRANSACTION;

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('mededu', '医療・保育・教育機関等連携加算', '医療・保育・教育機関等連携加算', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'mededu_tsuuin', '医療・保育・教育機関等連携加算（通院同行）', '通院同行', 90, 90, '確定条件:
- モニタリング月または計画作成月の病院等への通院同行で候補に残す
- 後段では同月3回までと同一病院等は月1回までを確認する

仮置き:
- 診療所は病院と同じ扱いで判定する
- 初回加算との関係はまだ後段へ未反映', 1 FROM addition AS a WHERE a.addition_code = 'mededu' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'mededu_info', '医療・保育・教育機関等連携加算（情報共有）', '情報共有', 100, 100, '確定条件:
- 情報共有で候補に残す
- 障害福祉サービスは除外する
- 後段では同グループ月1回までを確認する

仮置き:
- 元資料上は月区分の限定が薄いが、現段階では従来どおりモニタリング月または計画作成月に寄せている
- 機関グループの最終境界はまだ仮置き', 1 FROM addition AS a WHERE a.addition_code = 'mededu' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'mededu_interview', '医療・保育・教育機関等連携加算（面談）', '面談', 110, 110, '確定条件:
- 児対象のみ
- モニタリング月または計画作成月で候補に残す
- 面談のみ
- 必要な情報を受けた場合のみ
- 障害福祉サービスは除外する
- 同月1回まで
- 初回加算算定時は不可
- 担当者会議加算との併算定不可を後段で確認する

仮置き:
- 退院・退所加算との関係の細部はまだ未確定
- 対象機関を福祉サービス等提供機関だけに絞っているが、制度境界の細部は未確定', 1 FROM addition AS a WHERE a.addition_code = 'mededu' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'mededu_meeting', '医療・保育・教育機関等連携加算（会議）', '会議', 120, 120, '確定条件:
- 児対象のみ
- モニタリング月または計画作成月で候補に残す
- 会議のみ
- 必要な情報を受けた場合のみ
- 障害福祉サービスは除外する
- 同月1回まで
- 初回加算算定時は不可
- 担当者会議加算との併算定不可を後段で確認する

仮置き:
- 退院・退所加算との関係の細部はまだ未確定
- 対象機関を福祉サービス等提供機関だけに絞っているが、制度境界の細部は未確定', 1 FROM addition AS a WHERE a.addition_code = 'mededu' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('intensive', '集中支援加算', '集中支援加算', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_visit', '集中支援加算（訪問）', '訪問', 200, 200, '確定条件:
- それ以外月で候補に残す
- 訪問のみ
- 同月2回以上の訪問を後段で確認する

仮置き:
- 機関グループの範囲は仮置き', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_scene_check', '集中支援加算（サービス提供場面確認）', 'サービス提供場面確認', 210, 210, '確定条件:
- それ以外月で候補に残す
- サービス提供場面確認のみ

仮置き:
- 機関グループの範囲は仮置き', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_meeting_host', '集中支援加算（会議開催）', '担当者会議開催', 215, 215, '確定条件:
- それ以外月で候補に残す
- サービス担当者会議の開催のみ
- 旧資料上、追加の回数上限は見当たらない

仮置き:
- 現行UIでは「サービス担当者会議の開催」を「担当者会議開催」に寄せている', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_meeting_join', '集中支援加算（会議参加）', '会議', 220, 220, '確定条件:
- それ以外月で候補に残す
- 会議参加のみ
- 旧資料上、追加の回数上限は見当たらない

仮置き:
- 現行UIでは「会議参加」を「会議」に寄せている', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_tsuuin', '集中支援加算（通院同行）', '通院同行', 230, 230, '確定条件:
- それ以外月の病院等への通院同行のみ候補に残す
- 後段では同月3回までと同一病院等は月1回までを確認する', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_info', '集中支援加算（情報共有）', '情報共有', 240, 240, '確定条件:
- それ以外月で候補に残す
- 福祉サービス等提供機関への情報共有のみ
- 後段では同グループ月1回までを確認する

仮置き:
- 病院・訪看・薬局は内部的に別枝へ分けている', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_info_medical', '集中支援加算（情報共有）', '情報共有', 241, 241, '確定条件:
- それ以外月で候補に残す
- 病院または訪問看護への情報共有のみ
- 入院に当たっての情報共有は除外する
- 後段では同グループ月1回までを確認する

仮置き:
- 薬局は別枝へ分けて、入院確認の質問対象から外している', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'intensive_info_pharmacy', '集中支援加算（情報共有）', '情報共有', 242, 242, '確定条件:
- それ以外月で候補に残す
- 薬局への情報共有のみ
- 後段では同グループ月1回までを確認する

仮置き:
- 薬局は病院/訪看枝と分けて、入院確認の質問を出さない', 1 FROM addition AS a WHERE a.addition_code = 'intensive' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('monitoring', 'モニタリング加算', 'モニタリング加算', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'monitoring', 'モニタリング加算', 'サービス提供場面確認', 250, 250, '確定条件:
- 提供現場の訪問確認で候補に残す
- モニタリング月に限定しない
- 同月1回まで

仮置き:
- 現行UIでは「提供現場訪問」を「サービス提供場面確認」に寄せている
- 対象機関と対象サービスの制度境界はまだ仮置き', 1 FROM addition AS a WHERE a.addition_code = 'monitoring' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('conference', '担当者会議加算', '担当者会議加算', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'conference', '担当者会議加算', '担当者会議開催', 300, 300, '確定条件:
- モニタリング月のみ
- 福祉サービス等提供機関のみ
- 担当者会議開催のみ
- 同月1回まで
- 医保教（面談・会議）との併算定不可を後段で確認する', 1 FROM addition AS a WHERE a.addition_code = 'conference' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('discharge', '退院・退所加算', '退院・退所加算', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'discharge', '退院・退所加算', '面談 / 退院前面談', 400, 400, '確定条件:
- モニタリング月以外で候補に残す
- 退院・退所対象施設の職員との対面面談のみ
- 場所は限定しない
- 必要な情報を受けた場合のみ
- サービス等の利用開始月の調整のみ
- 同一の入所・入院期間中は3回まで
- 初回加算算定時は不可

仮置き:
- 現行UIでは旧ラベルの「退院前面談」も面談として受ける
- 入所施設、更生施設、児童施設、刑事施設等は名称推定に強い語だけを使っている', 1 FROM addition AS a WHERE a.addition_code = 'discharge' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('hospital_info_i', '入院時情報連携加算 I', '入院時情報連携加算 I', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'hospital_info_i', '入院時情報連携加算 I', '情報共有', 350, 350, '確定条件:
- 入院に当たって病院へ訪問して必要情報を提供した場合に候補に残す
- サービス判定区分では限定しない
- 同月1回まで
- IIとの併算定不可

仮置き:
- 現行UIでは「訪問情報提供」を「外出先 + 情報共有」に寄せている
- 診療所は病院と同じ扱いで判定する', 1 FROM addition AS a WHERE a.addition_code = 'hospital_info_i' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('hospital_info_ii', '入院時情報連携加算 II', '入院時情報連携加算 II', '児者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'hospital_info_ii', '入院時情報連携加算 II', '情報共有', 360, 360, '確定条件:
- 入院に当たって病院へ訪問以外の方法で必要情報を提供した場合に候補に残す
- サービス判定区分では限定しない
- 同月1回まで
- Iとの併算定不可

仮置き:
- 現行UIでは「訪問以外情報提供」を「自事業所内 + 情報共有」に寄せている
- 診療所は病院と同じ扱いで判定する', 1 FROM addition AS a WHERE a.addition_code = 'hospital_info_ii' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('edu_support', '保・教支援', '保・教支援', '児', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'edu_info', '保・教支援（情報共有）', '情報共有', 500, 500, '確定条件:
- 児対象のみ
- 障害福祉以外の福祉サービスの利用文脈で候補に残す
- 学校・保育・児童施設への情報共有で候補に残す
- 企業・就業生活支援センター等は新規雇用文脈のときだけ残す

仮置き:
- 集団生活施設など、学校・保育以外の対象境界はまだ仮置き', 1 FROM addition AS a WHERE a.addition_code = 'edu_support' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'edu_visit', '保・教支援（訪問面接）', '面談', 510, 510, '確定条件:
- 児対象のみ
- それ以外月のみ
- 障害福祉以外の福祉サービスの利用文脈で候補に残す
- 学校・保育・児童施設への訪問面接で候補に残す
- 企業・就業生活支援センター等は新規雇用文脈のときだけ残す

仮置き:
- 現行UIでは「訪問面接」を「外出先 + 面談」に寄せている
- 集団生活施設など、学校・保育以外の対象境界はまだ仮置き
- 旧の総称記録は訪問面接の回数へ自動換算していない', 1 FROM addition AS a WHERE a.addition_code = 'edu_support' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'edu_meeting', '保・教支援（会議参加）', '会議', 520, 520, '確定条件:
- 児対象のみ
- それ以外月のみ
- 障害福祉以外の福祉サービスの利用文脈で候補に残す
- 学校・保育・児童施設との会議参加で候補に残す
- 企業・就業生活支援センター等は新規雇用文脈のときだけ残す

仮置き:
- 現行UIでは「会議参加」を「会議」に寄せている
- 集団生活施設など、学校・保育以外の対象境界はまだ仮置き', 1 FROM addition AS a WHERE a.addition_code = 'edu_support' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('home_collab', '居宅連携', '居宅連携', '者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_info', '居宅連携（情報共有）', '情報共有', 600, 600, '確定条件:
- 者対象のみ
- ケアマネ事業所への情報共有で候補に残す
- ケアマネ利用開始時のみ
- 後段では同月2回までを確認する', 1 FROM addition AS a WHERE a.addition_code = 'home_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_visit', '居宅連携（訪問面接）', '面談', 610, 610, '確定条件:
- 者対象のみ
- それ以外月のみ
- ケアマネ事業所への訪問面接で候補に残す
- ケアマネ利用開始時のみ
- 後段では同月2回以上の訪問面接を確認する

仮置き:
- 現行UIでは「訪問面接」を「外出先 + 面談」に寄せている
- 旧の総称記録は訪問面接の回数へ自動換算していない', 1 FROM addition AS a WHERE a.addition_code = 'home_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_meeting', '居宅連携（会議参加）', '会議', 620, 620, '確定条件:
- 者対象のみ
- それ以外月のみ
- ケアマネ事業所との会議参加で候補に残す
- ケアマネ利用開始時のみ

仮置き:
- 現行UIでは「会議参加」を「会議」に寄せている', 1 FROM addition AS a WHERE a.addition_code = 'home_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

INSERT INTO addition (addition_code, addition_name, short_name, target_scope, prompt_template, note, is_active) VALUES ('home_work_collab', '居宅連携（就労）', '居宅連携（就労）', '者', NULL, 'Generated from app/frontend/app.js prototype branch definitions.', 1) ON DUPLICATE KEY UPDATE addition_name = VALUES(addition_name), short_name = VALUES(short_name), target_scope = VALUES(target_scope), prompt_template = VALUES(prompt_template), note = VALUES(note), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_work_info', '居宅連携（就労）（情報共有）', '情報共有', 700, 700, '確定条件:
- 者対象のみ
- 企業または障害者就業・生活支援センター等への情報共有で候補に残す
- 新規雇用開始時のみ
- 後段では同月2回までを確認する', 1 FROM addition AS a WHERE a.addition_code = 'home_work_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_work_visit', '居宅連携（就労）（訪問面接）', '面談', 710, 710, '確定条件:
- 者対象のみ
- それ以外月のみ
- 企業または障害者就業・生活支援センター等への訪問面接で候補に残す
- 新規雇用開始時のみ
- 後段では同月2回以上の訪問面接を確認する

仮置き:
- 現行UIでは「訪問面接」を「外出先 + 面談」に寄せている
- 旧の総称記録は訪問面接の回数へ自動換算していない', 1 FROM addition AS a WHERE a.addition_code = 'home_work_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);
INSERT INTO addition_branch (addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active) SELECT a.addition_id, 'home_work_meeting', '居宅連携（就労）（会議参加）', '会議', 720, 720, '確定条件:
- 者対象のみ
- それ以外月のみ
- 企業または障害者就業・生活支援センター等との会議参加で候補に残す
- 新規雇用開始時のみ

仮置き:
- 現行UIでは「会議参加」を「会議」に寄せている', 1 FROM addition AS a WHERE a.addition_code = 'home_work_collab' ON DUPLICATE KEY UPDATE addition_id = VALUES(addition_id), branch_name = VALUES(branch_name), branch_type = VALUES(branch_type), priority = VALUES(priority), auto_confirm_priority = VALUES(auto_confirm_priority), description = VALUES(description), is_active = VALUES(is_active);

COMMIT;
