-- Generated by v3/scripts/generate_relation_seed_from_review.py
-- Generated at: 2026-03-15T01:55:55+09:00

SET NAMES utf8mb4;
START TRANSACTION;

-- organization_service

-- client_enrollment

COMMIT;
