const fs = require("fs");
const path = require("path");
const vm = require("vm");

const workspaceRoot = path.resolve(__dirname, "..");
const appJsPath = path.join(workspaceRoot, "app", "frontend", "app.js");
const sourceAssetPath = path.join(workspaceRoot, "runtime", "prototype", "prototype-rule-source.js");
const outputDir = path.join(workspaceRoot, "runtime", "import");
const outputJsonPath = path.join(outputDir, "prototype_addition_catalog.json");
const outputSqlPath = path.join(outputDir, "prototype_addition_seed.sql");
const outputDbSqlPath = path.join(workspaceRoot, "db", "004_seed_prototype_additions.sql");

function readPrototypeSourceFromAsset() {
  if (!fs.existsSync(sourceAssetPath)) {
    return null;
  }

  const source = fs.readFileSync(sourceAssetPath, "utf8");
  const sandbox = {};
  vm.runInNewContext(source, sandbox, { timeout: 1000 });
  return sandbox.__KASAN_PROTOTYPE_RULE_SOURCE__ ?? sandbox.window?.__KASAN_PROTOTYPE_RULE_SOURCE__ ?? null;
}

function readPrototypeData() {
  const sourceAsset = readPrototypeSourceFromAsset();
  if (sourceAsset?.data && typeof sourceAsset.data === "object") {
    return sourceAsset.data;
  }

  const source = fs.readFileSync(appJsPath, "utf8");
  const match = source.match(/const data = ([\s\S]*?)\r?\n\r?\nconst baseReportViews =/);

  if (!match) {
    throw new Error("app.js から prototype data を抽出できませんでした。");
  }

  const literal = match[1].trim().replace(/;$/, "");
  const sandbox = {};
  vm.runInNewContext(`result = ${literal};`, sandbox, { timeout: 1000 });
  return sandbox.result;
}

function deriveTargetScope(targetTypes) {
  const normalized = Array.isArray(targetTypes)
    ? targetTypes.map((item) => String(item ?? "").trim()).filter(Boolean)
    : [];

  if (normalized.length === 0) {
    return null;
  }

  const only = Array.from(new Set(normalized));
  if (only.length === 1) {
    if (only[0] === "児") {
      return "児";
    }
    if (only[0] === "者") {
      return "者";
    }
  }
  return "児者";
}

function deriveBranchType(addition) {
  const actionTypes = Array.isArray(addition.actionTypes)
    ? addition.actionTypes.map((item) => String(item ?? "").trim()).filter(Boolean)
    : [];
  if (actionTypes.length === 1) {
    return actionTypes[0];
  }
  if (actionTypes.length > 1) {
    return actionTypes.join(" / ");
  }
  return addition.ruleStatus ? String(addition.ruleStatus).trim() : null;
}

function normalizePriority(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return 9999;
  }
  return Math.round(numeric * 10);
}

function buildBranchDescription(addition) {
  const lines = [];
  const confirmedRules = Array.isArray(addition.confirmedRules) ? addition.confirmedRules : [];
  const provisionalRules = Array.isArray(addition.provisionalRules) ? addition.provisionalRules : [];

  if (confirmedRules.length > 0) {
    lines.push("確定条件:");
    confirmedRules.forEach((rule) => lines.push(`- ${String(rule).trim()}`));
  }

  if (provisionalRules.length > 0) {
    if (lines.length > 0) {
      lines.push("");
    }
    lines.push("仮置き:");
    provisionalRules.forEach((rule) => lines.push(`- ${String(rule).trim()}`));
  }

  return lines.join("\n");
}

function escapeSql(value) {
  return String(value ?? "").replace(/\\/g, "\\\\").replace(/'/g, "''");
}

function buildCatalog(additions) {
  const families = new Map();

  additions.forEach((addition) => {
    const familyCode = String(addition.additionFamilyCode || addition.additionCode || "").trim();
    if (!familyCode) {
      return;
    }

    const familyName = String(addition.additionFamilyName || addition.additionName || "").trim();
    const targetScope = deriveTargetScope(addition.targetTypes);

    if (!families.has(familyCode)) {
      families.set(familyCode, {
        additionCode: familyCode,
        additionName: familyName,
        shortName: familyName,
        targetScope,
        note: "Generated from app/frontend/app.js prototype branch definitions.",
        branches: [],
      });
    }

    const family = families.get(familyCode);
    if (!family.targetScope && targetScope) {
      family.targetScope = targetScope;
    }

    family.branches.push({
      branchCode: String(addition.additionCode || "").trim(),
      branchName: String(addition.additionName || "").trim(),
      branchType: deriveBranchType(addition),
      priority: normalizePriority(addition.priority),
      autoConfirmPriority: normalizePriority(addition.priority),
      description: buildBranchDescription(addition),
    });
  });

  return {
    generatedAt: new Date().toISOString(),
    source: path.relative(workspaceRoot, appJsPath).replace(/\\/g, "/"),
    families: Array.from(families.values()),
  };
}

function buildSeedSql(catalog) {
  const lines = [];
  lines.push("-- Generated by v3/scripts/export_prototype_rule_catalog.js");
  lines.push("-- Seeds prototype addition families and branches into addition / addition_branch.");
  lines.push("START TRANSACTION;");
  lines.push("");

  catalog.families.forEach((family) => {
    lines.push(
      `INSERT INTO addition (addition_code, addition_name, short_name, target_scope, note, is_active) VALUES (` +
      `'${escapeSql(family.additionCode)}', ` +
      `'${escapeSql(family.additionName)}', ` +
      `'${escapeSql(family.shortName)}', ` +
      `${family.targetScope ? `'${escapeSql(family.targetScope)}'` : "NULL"}, ` +
      `'${escapeSql(family.note)}', 1)` +
      ` ON DUPLICATE KEY UPDATE ` +
      `addition_name = VALUES(addition_name), ` +
      `short_name = VALUES(short_name), ` +
      `target_scope = VALUES(target_scope), ` +
      `note = VALUES(note), ` +
      `is_active = VALUES(is_active);`
    );

    family.branches.forEach((branch) => {
      lines.push(
        `INSERT INTO addition_branch (` +
        `addition_id, branch_code, branch_name, branch_type, priority, auto_confirm_priority, description, is_active` +
        `) SELECT ` +
        `a.addition_id, ` +
        `'${escapeSql(branch.branchCode)}', ` +
        `'${escapeSql(branch.branchName)}', ` +
        `${branch.branchType ? `'${escapeSql(branch.branchType)}'` : "NULL"}, ` +
        `${Number(branch.priority)}, ` +
        `${Number(branch.autoConfirmPriority)}, ` +
        `${branch.description ? `'${escapeSql(branch.description)}'` : "NULL"}, ` +
        `1 ` +
        `FROM addition AS a ` +
        `WHERE a.addition_code = '${escapeSql(family.additionCode)}' ` +
        `ON DUPLICATE KEY UPDATE ` +
        `addition_id = VALUES(addition_id), ` +
        `branch_name = VALUES(branch_name), ` +
        `branch_type = VALUES(branch_type), ` +
        `priority = VALUES(priority), ` +
        `auto_confirm_priority = VALUES(auto_confirm_priority), ` +
        `description = VALUES(description), ` +
        `is_active = VALUES(is_active);`
      );
    });

    lines.push("");
  });

  lines.push("COMMIT;");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const data = readPrototypeData();
  const additions = Array.isArray(data.additions) ? data.additions : [];
  const catalog = buildCatalog(additions);

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outputJsonPath, JSON.stringify(catalog, null, 2) + "\n", "utf8");
  const sql = buildSeedSql(catalog);
  fs.writeFileSync(outputSqlPath, sql, "utf8");
  fs.writeFileSync(outputDbSqlPath, sql, "utf8");

  process.stdout.write(
    `catalog: ${path.relative(workspaceRoot, outputJsonPath)}\n` +
    `seed: ${path.relative(workspaceRoot, outputSqlPath)}\n` +
    `db-seed: ${path.relative(workspaceRoot, outputDbSqlPath)}\n` +
    `families: ${catalog.families.length}\n` +
    `branches: ${catalog.families.reduce((sum, family) => sum + family.branches.length, 0)}\n`
  );
}

main();
