#!/usr/bin/env python3
"""Generate reviewed relation seed SQL from review CSV files."""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Sequence


def sql_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "''")
    return "'" + escaped + "'"


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    base_dir = Path(__file__).resolve().parents[1]
    runtime_dir = base_dir / "runtime" / "import"
    parser = argparse.ArgumentParser(description="Generate relation seed SQL from reviewed CSVs.")
    parser.add_argument(
        "--organization-review",
        type=Path,
        default=runtime_dir / "organization_service_review.csv",
        help="Reviewed organization_service CSV.",
    )
    parser.add_argument(
        "--enrollment-review",
        type=Path,
        default=runtime_dir / "client_enrollment_review.csv",
        help="Reviewed client_enrollment CSV.",
    )
    parser.add_argument(
        "--output-sql",
        type=Path,
        default=runtime_dir / "relation_seed_reviewed.sql",
        help="Output SQL path.",
    )
    return parser.parse_args(argv)


def parse_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def split_codes(raw_value: str) -> List[str]:
    normalized = raw_value.replace(";", ",").replace("|", ",").replace(" ", ",")
    return [item.strip() for item in normalized.split(",") if item.strip()]


def organization_service_statement(row: Dict[str, str], service_code: str) -> str:
    note_parts = ["reviewed import"]
    if row.get("note"):
        note_parts.append(row["note"])
    note_sql = sql_quote(" / ".join(note_parts))
    return f"""INSERT INTO `organization_service` (`organization_id`, `service_definition_id`, `is_active`, `note`)
SELECT o.organization_id, sd.service_definition_id, 1, {note_sql}
FROM organization AS o
INNER JOIN service_definition AS sd
  ON sd.service_code = {sql_quote(service_code)}
WHERE o.organization_code = {sql_quote(row['organization_code'])}
  AND NOT EXISTS (
    SELECT 1
    FROM organization_service AS os
    WHERE os.organization_id = o.organization_id
      AND os.service_definition_id = sd.service_definition_id
  );"""


def client_enrollment_statement(row: Dict[str, str]) -> str:
    started_on = row.get("started_on", "").strip()
    ended_on = row.get("ended_on", "").strip()
    confirmed_group_name = row.get("confirmed_group_name", "").strip()
    note_parts = ["reviewed import"]
    if row.get("note"):
        note_parts.append(row["note"])
    if confirmed_group_name:
        note_parts.append(f"group={confirmed_group_name}")
    note_sql = sql_quote(" / ".join(note_parts))
    started_sql = sql_quote(started_on) if started_on else "NULL"
    ended_sql = sql_quote(ended_on) if ended_on else "NULL"
    service_group_sql = (
        f"""(
    SELECT sg.service_group_id
    FROM service_group AS sg
    WHERE sg.organization_service_id = os.organization_service_id
      AND sg.group_name = {sql_quote(confirmed_group_name)}
    LIMIT 1
  )"""
        if confirmed_group_name
        else "NULL"
    )
    return f"""INSERT INTO `client_enrollment` (`client_id`, `organization_service_id`, `service_group_id`, `started_on`, `ended_on`, `is_active`, `note`)
SELECT c.client_id, os.organization_service_id, {service_group_sql}, {started_sql}, {ended_sql}, 1, {note_sql}
FROM client AS c
INNER JOIN organization AS o
  ON o.organization_code = {sql_quote(row['organization_code'])}
INNER JOIN service_definition AS sd
  ON sd.service_code = {sql_quote(row['confirmed_service_code'])}
INNER JOIN organization_service AS os
  ON os.organization_id = o.organization_id
 AND os.service_definition_id = sd.service_definition_id
WHERE c.client_code = {sql_quote(row['client_code'])}
  AND NOT EXISTS (
    SELECT 1
    FROM client_enrollment AS ce
    WHERE ce.client_id = c.client_id
      AND ce.organization_service_id = os.organization_service_id
      AND ((ce.service_group_id IS NULL AND {service_group_sql} IS NULL) OR ce.service_group_id = {service_group_sql})
  );"""


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)
    organization_rows = parse_csv(args.organization_review) if args.organization_review.is_file() else []
    enrollment_rows = parse_csv(args.enrollment_review) if args.enrollment_review.is_file() else []

    statements: List[str] = [
        "-- Generated by v3/scripts/generate_relation_seed_from_review.py",
        f"-- Generated at: {datetime.now().astimezone().isoformat(timespec='seconds')}",
        "",
        "SET NAMES utf8mb4;",
        "START TRANSACTION;",
        "",
        "-- organization_service",
    ]

    organization_insert_count = 0
    for row in organization_rows:
        if row.get("review_status", "").strip().lower() in {"skip", "保留"}:
            continue
        for service_code in split_codes(row.get("confirmed_service_codes", "")):
            statements.append(organization_service_statement(row, service_code))
            organization_insert_count += 1

    statements.extend(["", "-- client_enrollment"])

    enrollment_insert_count = 0
    for row in enrollment_rows:
        confirmed_service_code = row.get("confirmed_service_code", "").strip()
        if not confirmed_service_code:
            continue
        if row.get("review_status", "").strip().lower() in {"skip", "保留"}:
            continue
        statements.append(client_enrollment_statement(row))
        enrollment_insert_count += 1

    statements.extend(["", "COMMIT;", ""])
    args.output_sql.parent.mkdir(parents=True, exist_ok=True)
    args.output_sql.write_text("\n".join(statements), encoding="utf-8")

    print("Generated:")
    print(f"  {args.output_sql}")
    print("Counts:")
    print(f"  organization_service statements: {organization_insert_count}")
    print(f"  client_enrollment statements: {enrollment_insert_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
